openapi: 3.0.0
info:
  title: Terra Resource Buffer Service API
  description: |
    Resource Buffering Service to allocate and buffer cloud resources
  version: 0.0.1

servers:
  - url: /

security:
  - bearerAuth: []
  - authorization: [openid, email, profile]

paths:
  '/status':
    get:
      security: []
      description: |
        Returns the operational status of the service
      operationId: serviceStatus
      tags:
        - unauthenticated
      responses:
        200:
          description: Service is functional
          $ref: '#/components/responses/StatusResponse'
        500:
          description: Service is broken
          $ref: '#/components/responses/StatusResponse'

  '/api/resource/v1/{projectId}/repair':
    post:
      summary: Re-enable any Google APIs that are disabled on this resource to match the original pool configuration.
      operationId: repairResource
      parameters:
        - $ref: '#/components/parameters/GoogleProjectUid'
#      requestBody:
#        required: true
#        content:
#          application/json:
#            schema:
#              $ref: '#/components/schemas/HandoutRequestBody'
      tags:
        - resource
      responses:
        '200':
          description: OK, resource is repaired.
#          content:
#            application/json:
#              schema:
#                $ref: '#/components/schemas/ResourceInfo'
        '404':
          description: Project id not found.
        '500':
          description: Get request error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorReport'

  '/api/pool/v1/{poolId}/resource':
    put:
      summary: Get a resource from pool and update the resource state, each handoutRequestId is assigned to the resource no more than once. Using the same handoutRequestId will get the same ResourceInfo
      operationId: handoutResource
      parameters:
        - $ref: '#/components/parameters/PoolId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HandoutRequestBody'
      tags:
        - buffer
      responses:
        '200':
          description: OK, using the same handoutRequestId will also get 200 back with the same ResourceInfo.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceInfo'
        '404':
          description: No resource available in this pool.
        '500':
          description: Get request error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorReport'

  '/api/pool/v1/{poolId}':
    get:
      summary: Get the pool info, including resource count in each state, and pool config.
      operationId: getPoolInfo
      parameters:
        - $ref: '#/components/parameters/PoolId'
      tags:
        - buffer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PoolInfo'
        '404':
          description: No resource available in this pool.
        '500':
          description: Get request error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorReport'

components:
  parameters:
    PoolId:
      name: poolId
      in: path
      description: |-
        Unique identity of a pool
      required: true
      schema:
        type: string

    GoogleProjectUid:
      name: projectId
      in: path
      description: |-
        Google Cloud Project ID
      required: true
      schema:
        type: string

  schemas:
    ErrorReport:
      type: object
      properties:
        message:
          type: string
        statusCode:
          type: integer
        causes:
          type: array
          items:
            type: string

    SystemStatus:
      type: object
      properties:
        ok:
          description: status of this service
          type: boolean
        systems:
          type: object
          additionalProperties:
            type: object
            properties:
              ok:
                type: boolean
              messages:
                type: array
                items:
                  type: string

    HandoutRequestBody:
      description: |-
        The request body for getting resource from Buffer Service
      type: object
      required:
        - handoutRequestId
      properties:
        handoutRequestId:
          description: |-
            The unique identifier presented by the client for a resource request.
            Using the same handoutRequestId in the same pool would ge the same resource back.
          type: string

    PoolConfigs:
      description: |-
        Terra Resource Buffer Service Reource Pools
      type: object
      required:
        - poolConfigs
      properties:
        poolConfigs:
          type: array
          items:
            $ref: '#/components/schemas/PoolConfig'

    PoolConfig:
      description: |-
        Terra Resource Buffer Service Reource Pool Config
        type: object
      required:
        - poolId
        - size
        - resourceConfigName
      properties:
        poolId:
          description: |
            A unique id for the pool. No two pools can ever have the same id. Any string is allowed.
          type: string
        size:
          description: |
            Maximum number of resources in the pool.
          type: integer
        resourceConfigName:
          description: |
            The config name the pool use. Resource Buffer Service will use it to locate the actual config file.
          type: string

    ResourceInfo:
      description: |-
        Information represents a resource in Resource Buffer Service
      type: object
      required:
        - poolId
        - requestHandoutId
        - cloudResourceUid
      properties:
        poolId:
          description: |
            The pool id the resource belongs to.
          type: string
        requestHandoutId:
          description: |
            The unique identifier used for handout resource. Resource Buffer Service will handout the same resource for the same id.
          type: string
        cloudResourceUid:
          $ref: '#/components/schemas/CloudResourceUid'

    PoolInfo:
      description: |-
        Information represents a pool in Resource Buffer Service
      type: object
      required:
        - poolId
        - status
      properties:
        poolConfig:
          $ref: '#/components/schemas/PoolConfig'
        status:
          $ref: '#/components/schemas/PoolStatus'
        resourceStateCount:
          description: |
            Number of resources in each state
          type: object
          additionalProperties:
            type: integer

    PoolStatus:
      description: Possible pool status.
      type: string
      enum:
        - ACTIVE
        - DEACTIVATED

    GoogleAiNotebookInstanceUid:
      type: object
      required:
      - projectId
      - location
      - instanceId
      properties:
        projectId:
          type: string
        location:
          description: The location of the instance, e.g. 'uswest1-b'.
          type: string
        instanceId:
          description: The user-provided instance id to identify the instance.
          type: string

    GoogleBigQueryDatasetUid:
      type: object
      required:
      - projectId
      - datasetId
      properties:
        projectId:
          type: string
        datasetId:
          type: string

    GoogleBigQueryTableUid:
      type: object
      required:
        - projectId
        - datasetId
        - tableId
      properties:
        projectId:
          type: string
        datasetId:
          type: string
        tableId:
          type: string

    GoogleBlobUid:
      type: object
      required:
        - bucketName
        - blobName
      properties:
        bucketName:
          type: string
        blobName:
          type: string

    GoogleBucketUid:
      type: object
      required:
        - bucketName
      properties:
        bucketName:
          type: string

    GoogleProjectUid:
      type: object
      required:
        - projectId
      properties:
        projectId:
          type: string

    AzureResourceGroup:
      type: object
      required:
      - tenantId
        - subscriptionId
      - resourceGroupName
      properties:
        tenantId:
          description: The tenant ID.
          type: string
        subscriptionId:
          description: The subscription ID.
          type: string
        resourceGroupName:
          description: Name of the resource group.
          type: string

    AzureDisk:
      type: object
      required:
      - resourceGroup
      - diskName
      properties:
        resourceGroup:
          $ref: '#/components/schemas/AzureResourceGroup'
        diskName:
          description: The user-provided name to identify the disk.
          type: string

    AzureVirtualMachine:
      type: object
      required:
      - resourceGroup
      - vmName
      properties:
        resourceGroup:
          $ref: '#/components/schemas/AzureResourceGroup'
        vmName:
          description: The user-provided name to identify the VM.
          type: string

    # A cloud resource unique identifier. Each CloudResourceUid represents exactly one cloud resource.
    # We are not doing polymorphism at this moment because of lack of support in swagger-codegen or openApiGenerator
    # Now CloudResourceUid contains all possible cloud resource types, and we will assume there is only one being set
    # when using this.
    # Currently the only resource that Buffer supports is GcpProject.
    CloudResourceUid:
      type: object
      properties:
        googleAiNotebookInstanceUid:
          $ref: '#/components/schemas/GoogleAiNotebookInstanceUid'
        googleBigQueryDatasetUid:
          $ref: '#/components/schemas/GoogleBigQueryDatasetUid'
        googleBigQueryTableUid:
          $ref: '#/components/schemas/GoogleBigQueryTableUid'
        googleBlobUid:
          $ref: '#/components/schemas/GoogleBlobUid'
        googleBucketUid:
          $ref: '#/components/schemas/GoogleBucketUid'
        googleProjectUid:
          $ref: '#/components/schemas/GoogleProjectUid'
        azureDisk:
          $ref: '#/components/schemas/AzureDisk'
        azureVirtualMachine:
          $ref: '#/components/schemas/AzureVirtualMachine'

  responses:
    ErrorResponse:
      description: common error response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorReport'

    StatusResponse:
      description: common status response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SystemStatus'

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    authorization:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            openid: open id authorization
            email: email authorization
            profile: profile authorization
