name: 'write-credentials'
description: |
  Collect the needed credentials for integration testing and place them in a
  directory named "rendered". Note that all of these secrets are
  assumed to be base64-encoded JSON service account keys.
inputs:
  buffer-app-sa-b64:
    description: 'Base64-encoded buffer (RBS) service account'
    required: true
  janitor-sa-b64:
    description: 'Base64-encoded CRL Janitor service account'
    required: true

runs:
  using: "composite"
  steps:
    - name: Write credentials
      id: 'setup-user-delegated-creds'
      run: |
        mkdir -p rendered
        
        BUFFER_APP_SA_B64=${{ inputs.buffer-app-sa-b64 }}
        echo ::add-mask::BUFFER_APP_SA_B64
        BUFFER_APP_SA=$(echo $BUFFER_APP_SA_B64 | base64 --decode)
        echo ::add-mask::$BUFFER_APP_SA
        echo $BUFFER_APP_SA > rendered/sa-account.json  
        
        JANITOR_SA_B64=${{ inputs.janitor-sa-b64 }}
        echo ::add-mask::$JANITOR_SA_B64
        JANITOR_SA=$(echo $JANITOR_SA_B64 | base64 --decode)
        echo ::add-mask::$JANITOR_SA
        echo $JANITOR_SA > rendered/janitor-client-sa-account.json
      shell: bash
