# Community Workbench buffered workspace template
---
configName: "cwb_ws_resource_quality_v10"
gcpProjectConfig:
  projectIdSchema:
    prefix: "terra-quality"
    scheme: "RANDOM_CHAR"
  # quality.firecloud.org/quality/CommunityWorkbench
  parentFolderId: "180789000311"
  billingAccount: "01A82E-CA8A14-367457"
  enabledApis:
    - "bigquery-json.googleapis.com"
    - "compute.googleapis.com"
    - "container.googleapis.com"
    - "cloudbilling.googleapis.com"
    - "clouderrorreporting.googleapis.com"
    - "cloudkms.googleapis.com"
    - "cloudtrace.googleapis.com"
    - "containerregistry.googleapis.com"
    - "dataflow.googleapis.com"
    - "dataproc.googleapis.com"
    - "dns.googleapis.com"
    - "lifesciences.googleapis.com"
    - "logging.googleapis.com"
    - "monitoring.googleapis.com"
    - "storage-api.googleapis.com"
    - "storage-component.googleapis.com"
    - "networkmanagement.googleapis.com"
    - "iap.googleapis.com"
  network:
    enableNetworkMonitoring: "false"
    enablePrivateGoogleAccess: "true"
  kubernetesEngine:
    createGkeDefaultServiceAccount: "true"
  computeEngine:
    keepDefaultServiceAcct: "true"
