# Projects with VPC-SC configuration
---
configName: "vpc_sc_v11"
gcpProjectConfig:
  projectIdSchema:
    prefix: "terra-vpc-sc"
    scheme: "RANDOM_CHAR"
  # firecloud.org/prod/for_vpc_sc_unclaimed
  parentFolderId: "160283235721"
  billingAccount: "0106B0-41CAA9-427C96"
  enabledApis:
    - "bigquery-json.googleapis.com"
    - "compute.googleapis.com"
    - "container.googleapis.com"
    - "cloudbilling.googleapis.com"
    - "clouderrorreporting.googleapis.com"
    - "cloudkms.googleapis.com"
    - "cloudtrace.googleapis.com"
    - "containerregistry.googleapis.com"
    - "dataflow.googleapis.com"
    - "dataproc.googleapis.com"
    - "dns.googleapis.com"
    - "lifesciences.googleapis.com"
    - "logging.googleapis.com"
    - "monitoring.googleapis.com"
    - "serviceusage.googleapis.com"
    - "storage-api.googleapis.com"
    - "storage-component.googleapis.com"
  network:
    enableNetworkMonitoring: "true"
    enablePrivateGoogleAccess: "true"
    enableCloudRegistryPrivateGoogleAccess: "true"
    enableArtifactRegistryPrivateGoogleAccess: "true"
    blockBatchInternetAccess: "true"
  kubernetesEngine:
    createGkeDefaultServiceAccount: "true"
  serviceUsage:
    bigQuery:
      overrideBigQueryDailyUsageQuota: true
      bigQueryDailyUsageQuotaOverrideValueMebibytes: 38146972 # 40 TB
  securityGroup: "high"
