# This workflow will build a Java project with Gradle
# Copied from Janitor(https://github.com/DataBiosphere/terra-resource-janitor) and similar to all other MCTerra servers.
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Run Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '**' ]
env:
  VAULT_ADDR: https://clotho.broadinstitute.org:8200
jobs:
  unit-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12.3
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - name: Pull Vault image
        run: docker pull vault:1.1.0
      # Currently, there's no way to add capabilities to Docker actions on Git, and Vault needs IPC_LOCK to run.
      - name: Get Vault token
        id: vault-token-step
        run: |
          VAULT_TOKEN=$(docker run --rm --cap-add IPC_LOCK \
            -e "VAULT_ADDR=${VAULT_ADDR}" \
            vault:1.1.0 \
            vault write -field token \
              auth/approle/login role_id=${{ secrets.VAULT_APPROLE_ROLE_ID }} \
              secret_id=${{ secrets.VAULT_APPROLE_SECRET_ID }})
          echo ::set-output name=vault-token::$VAULT_TOKEN
          echo ::add-mask::$VAULT_TOKEN
      - name: Grant execute permission for render-config
        run: chmod +x local-dev/render-config.sh
      - name: Render configuration for tests
        run: local-dev/render-config.sh ${{ steps.vault-token-step.outputs.vault-token }}
      - name: Initialize Postgres DB
        env:
          PGPASSWORD: postgres
        run: psql -h 127.0.0.1 -U postgres -f ./local-dev/local-postgres-init.sql
      - name: Set up AdoptOpenJDK 11
        uses: joschi/setup-jdk@v2
        with:
          java-version: 11
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: v1-${{ runner.os }}-gradle-${{ hashfiles('**/gradle-wrapper.properties') }}-${{ hashFiles('**/*.gradle') }}
          restore-keys: v1-${{ runner.os }}-gradle-${{ hashfiles('**/gradle-wrapper.properties') }}
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Check Javadoc
        run: ./gradlew javadoc --scan
      - name: Run unit tests
        id: unit-test
        run: ./gradlew unitTest --scan
      - name: Run integration tests
        id: integration-test
        run: ./gradlew integrationTest --scan
      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: Test Reports
          path: build/reports
      - name: Upload Jacoco Reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Test Reports
          path: build/jacoco
